---
title : "The Pha Chuk Hydro Power Plant (PCK) generation profile"
author: "Puttipong Chunark, Jirayus Boonyapen, Newin Phongkasemwiwat"
date  : "July 22, 2023"
output:
  html_document: default
  pdf_document: default
---

```{r librarysetting, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggtext)
library(plotly)
```

```{r themesetting, echo=FALSE, warning=FALSE, message=FALSE}
ThemeLine <- 
  theme_bw() +
  theme(
    panel.border=element_rect(fill=NA),
    panel.grid.minor = element_line(color = NA), 
    #    axis.title=element_text(size=5),
    #    axis.text.x = element_text(hjust=1,size = 10, angle = 0),
    axis.line=element_line(colour="black"),
    panel.background=element_rect(fill = "white"),
    panel.grid.major.x=element_line(linetype="dashed",colour="grey",linewidth = 0.5),
    panel.grid.major.y = element_blank(),
    # panel.grid.major=element_blank(),
    strip.background=element_rect(fill="white", colour="white"),
    strip.text.x = element_text(size=10, colour = "black", angle = 0,face="bold"),
    axis.text.x=element_text(size = 10,angle=45, vjust=0.9, hjust=1, margin = unit(c(t = 0.3, r = 0, b = 0, l = 0), "cm")),
    axis.text.y=element_text(size = 10,margin = unit(c(t = 0, r = 0.3, b = 0, l = 0), "cm")),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10),
    axis.ticks.length=unit(-0.15,"cm")
  )
linepalette1 <- c("#4DAF4A","#FF7F00","#377EB8","#E41A1C","#984EA3","#F781BF","#8DD3C7","#FB8072","#80B1D3","#FDB462","#B3DE69","#FCCDE5","#D9D9D9","#BC80BD","#CCEBC5","#FFED6F","#7f878f","#A65628","#FFFF33")
linepalette2 <- c("#E41A1C","#FF7F00","#377EB8","#B3DE69","#4DAF4A","#984EA3","#F781BF","#8DD3C7","#FB8072","#80B1D3","#FDB462","#FCCDE5","#D9D9D9","#BC80BD","#CCEBC5","#FFED6F","#7f878f","#A65628","#FFFF33")

```

The Pha Chuk Hydro Power Plant (PCK) provides a capacity at 14 MW. The project is COD on 30 September 2022. The generation profile on National Control Center (NCC) is available from 22 November 2022.


```{r pckh1genprofile2022, echo=FALSE, message=FALSE, warning=FALSE}
pckh1profile2022 <-
  read_excel("rawdata/PCK_H1_01012022_31122022.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")
```

```{r pckh2genprofile2022, echo=FALSE, message=FALSE, warning=FALSE}
pckh2profile2022 <-
  read_excel("rawdata/PCK_H2_01012022_31122022.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")
```


```{r plot_pckh1minegtnetgen2022, echo=FALSE, warning=FALSE, message=FALSE}
ggplotly(
  pckh1profile2022 %>% 
  filter(day == 1 & month == 1 & year == 2022) %>% 
  ggplot(aes(x = timestamp, y = pck_h1))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2022 Pha Chuk H1 Hydro Power Plant gen. profile \nat <span style = 'color: red'>minimum EGAT net gen.</span> at <span style = 'color: dodgerblue'> 9,876 MW </span> on <span style = 'color: red'> 1 Jan 2021 @ 12:30 PM </span>")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
) %>%
style(showlegend = FALSE)
```

```{r plot_mklminegtnetgen2022, echo=FALSE, warning=FALSE, message=FALSE}
ggplotly(
  mklprofile2022 %>% 
  filter(day == 1 & month == 1 & year == 2022) %>% 
  ggplot(aes(x = timestamp, y = mkl_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2022 Mae Klong Hydro Power Plant gen. profile \nat <span style = 'color: red'>minimum EGAT net gen.</span> at <span style = 'color: dodgerblue'> 11,547.85 MW </span> on <span style = 'color: red'> 1 Jan 2022 @ 12:30 PM </span>")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
) %>%
style(showlegend = FALSE)
```

```{r plot_mklmaxegtnetgen2021, echo=FALSE, warning=FALSE, message=FALSE}
ggplotly(
  mklprofile2021 %>% 
  filter(day == 3 & month == 4 & year == 2021) %>% 
  ggplot(aes(x = timestamp, y = mkl_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2021 Mae Klong Hydro Power Plant gen. profile \nat <span style = 'color: red'>Peak EGAT net gen. </span> at <span style = 'color: dodgerblue'> 30,135 MW </span> on <span style = 'color: red'> 3 Apr 2021 @ 21:00 PM </span>")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )
) %>%
style(showlegend = FALSE)
```

```{r plot_mklmaxegtnetgen2022, echo=FALSE, warning=FALSE, message=FALSE}
ggplotly(
  mklprofile2022 %>% 
  filter(day == 27 & month == 4 & year == 2022) %>% 
  ggplot(aes(x = timestamp, y = mkl_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2022 Mae Klong Hydro Power Plant gen. profile \nat <span style = 'color: red'>Peak EGAT net gen. </span> at <span style = 'color: dodgerblue'> 32,254.5 MW </span> on <span style = 'color: red'> 27 Apr 2022 @ 22:30 PM </span>")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )
) %>%
style(showlegend = FALSE)
```