---
title: "The Lamtakong dam (LTK) generation profile"
author: "Generation System Development Planning Department"
date: "September 23, 2024"
output:
  pdf_document: default
  html_document: default
---

```{r librarysetting, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggtext)
library(plotly)
```

```{r themesetting, echo=FALSE, warning=FALSE, message=FALSE}
ThemeLine <- 
  theme_bw() +
  theme(
    panel.border=element_rect(fill=NA),
    panel.grid.minor = element_line(color = NA), 
    #    axis.title=element_text(size=5),
    #    axis.text.x = element_text(hjust=1,size = 10, angle = 0),
    axis.line=element_line(colour="black"),
    panel.background=element_rect(fill = "white"),
    panel.grid.major.x=element_line(linetype="dashed",colour="grey",linewidth = 0.5),
    panel.grid.major.y = element_blank(),
    # panel.grid.major=element_blank(),
    strip.background=element_rect(fill="white", colour="white"),
    strip.text.x = element_text(size=10, colour = "black", angle = 0,face="bold"),
    axis.text.x=element_text(size = 10,angle=45, vjust=0.9, hjust=1, margin = unit(c(t = 0.3, r = 0, b = 0, l = 0), "cm")),
    axis.text.y=element_text(size = 10,margin = unit(c(t = 0, r = 0.3, b = 0, l = 0), "cm")),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10),
    axis.ticks.length=unit(-0.15,"cm")
  )
linepalette1 <- c("#4DAF4A","#FF7F00","#377EB8","#E41A1C","#984EA3","#F781BF","#8DD3C7","#FB8072","#80B1D3","#FDB462","#B3DE69","#FCCDE5","#D9D9D9","#BC80BD","#CCEBC5","#FFED6F","#7f878f","#A65628","#FFFF33")
linepalette2 <- c("#E41A1C","#FF7F00","#377EB8","#B3DE69","#4DAF4A","#984EA3","#F781BF","#8DD3C7","#FB8072","#80B1D3","#FDB462","#FCCDE5","#D9D9D9","#BC80BD","#CCEBC5","#FFED6F","#7f878f","#A65628","#FFFF33")

```

```{r ltkgenprofile2019, echo=FALSE, message=FALSE, warning=FALSE}
ltkprofile2019 <-
  read_excel("rawdata/LTK_01012019_31122019.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")

```

```{r ltkgenprofile2020, echo=FALSE, message=FALSE, warning=FALSE}
ltkprofile2020 <-
  read_excel("rawdata/LTK_01012020_31122020.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")

```


```{r ltkgenprofile2021, echo=FALSE, message=FALSE, warning=FALSE}
ltkprofile2021 <-
  read_excel("rawdata/LTK_01012021_31122021.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")

```
```{r ltkgenprofile2022, echo=FALSE, message=FALSE, warning=FALSE}
ltkprofile2022 <-
  read_excel("rawdata/LTK_01012022_31122022.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")
```

```{r ltkgenprofile2023, echo=FALSE, message=FALSE, warning=FALSE}
ltkprofile2023 <-
  read_excel("rawdata/LTK_01012023_31122023.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")
```

```{r ltkgenprofile2024, echo=FALSE, message=FALSE, warning=FALSE}
ltkprofile2024 <-
  read_excel("rawdata/LTK_01012024_23092024.xlsx") %>% 
  rename_all(tolower) %>% 
  mutate(timestamp = as.POSIXct(timestamp, format = "%d-%b-%Y %H:%M", tz = "UTC"),
         date = as.Date(timestamp, format = "%d-%b-%Y"),
         time = format(as.POSIXct(timestamp), format = "%H:%M:%S"), 
         year = year(timestamp),
         month = month(timestamp),
         weekday = weekdays(timestamp),
         yday = yday(timestamp),
         day = day(timestamp),
         hour = hour(timestamp),
         minute = minute(timestamp)) %>% 
  filter(minute == "30" | minute =="0") %>% 
  mutate(season = if_else(month %in%c("3","4","5"), "Summer",
                          if_else(month %in% c("6","7","8","9","10"), "Rainy",
                          if_else(month %in% c("11","12","1","2"), "Winter", "Others"))),.after = "date")
```

```{r plot_ltkminegtnetgen2019, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2019 %>% 
  filter(day == 1 & month == 1 & year == 2019) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2019 Lamtakong Dam gen. profile \nat minimum EGAT net gen. at 10,523.8 MW on 1 Jan 2019 @ 12:00 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)")

```

```{r plot_ltkminegtnetgen2020, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2020 %>% 
  filter(day == 31 & month == 12 & year == 2020) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2020 Lamtakong Dam gen. profile \nat minimum EGAT net gen. at 11,530 MW on 31 Dec 2020 @ 01:00 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
```

```{r plot_ltkminegtnetgen2021, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2021 %>% 
  filter(day == 1 & month == 1 & year == 2021) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2021 Lamtakong Dam gen. profile \nat minimum EGAT net gen. at 9,876 MW on 1 Jan 2021 @ 12:30 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
```

```{r plot_ltkminegtnetgen2022, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2022 %>% 
  filter(day == 1 & month == 1 & year == 2022) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2022 Lamtakong Dam gen. profile \nat minimum EGAT net gen. at 11,547.85 MW on 1 Jan 2022 @ 12:30 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
```

```{r plot_ltkminegtnetgen2023, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2023 %>% 
  filter(day == 1 & month == 1 & year == 2023) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2023 Lamtakong Dam gen. profile \nat minimum EGAT net gen. at 10,557.60 MW on 1 Jan 2023 @ 12:30 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
```

```{r plot_ltkminegtnetgen2024, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2024 %>% 
  filter(day == 1 & month == 1 & year == 2024) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2024 Lamtakong Dam gen. profile \nat minimum EGAT net gen. at 13,645.15 MW on 1 Jan 2024 @ 09:00 AM")+
  labs(x = NULL,
       y = "Electricity generation (MW)")
```


```{r plot_ltkmaxegtnetgen2019, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2019 %>% 
  filter(day == 2 & month == 5 & year == 2019) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2019 Lamtakong Dam gen. profile \nat Peak EGAT net gen. at 30,853.2 MW on 2 May 2019 @ 10:30 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )

```

```{r plot_ltkmaxegtnetgen2020, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2020 %>% 
  filter(day == 12 & month == 3 & year == 2020) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2020 Lamtakong Dam gen. profile \nat Peak EGAT net gen. at 28,636.7 MW on 12 Mar 2020 @ 08:30 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )

```

```{r plot_ltkmaxegtnetgen2021, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2021 %>% 
  filter(day == 3 & month == 4 & year == 2021) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2021 Lamtakong Dam gen. profile \nat Peak EGAT net gen. at 30,135 MW on 3 Apr 2021 @ 09:00 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )

```

```{r plot_ltkmaxegtnetgen2022, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2022 %>% 
  filter(day == 27 & month == 4 & year == 2022) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2022 Lamtakong Dam gen. profile \nat Peak EGAT net gen. at 32,254.5 MW on 27 Apr 2022 @ 10:30 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )

```

```{r plot_ltkmaxegtnetgen2023, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2023 %>% 
  filter(day == 6 & month == 5 & year == 2023) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2023 Lamtakong Dam gen. profile \nat Peak EGAT net gen. at 34,130.5 MW on 6 May 2023 @ 09:41 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )

```

```{r plot_ltkmaxegtnetgen2024, echo=FALSE, warning=FALSE, message=FALSE}

  ltkprofile2024 %>% 
  filter(day == 29 & month == 4 & year == 2024) %>% 
  ggplot(aes(x = timestamp, y = ltk_h))+
  geom_line(aes(color = "red"),
            show.legend = FALSE)+
  geom_hline(yintercept = 0)+
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M")+
  ThemeLine+
  ggtitle("The 2024 Lamtakong Dam gen. profile \nat Peak EGAT net gen. at 36,477.80 MW on 29 April 2024 @ 08:56 PM")+
  labs(x = NULL,
       y = "Electricity generation (MW)"
       )

```


